# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-26 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('directors_name', models.CharField(max_length=255)),
                ('directors_phone', models.CharField(max_length=255)),
                ('directors_email', models.CharField(max_length=255)),
                ('last_calculation', models.DateTimeField()),
                ('servises', models.ManyToManyField(to='main.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('last_coming', models.DateTimeField()),
                ('own_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='StorageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StorageLogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='storagelog',
            name='log_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StorageLogType'),
        ),
    ]
