# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-26 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_storagelog_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 26, 16, 7, 1, 889513, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
