# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-26 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_storagelog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('custom_product', models.CharField(blank=True, max_length=255)),
                ('custom_price', models.CharField(blank=True, max_length=255)),
                ('custom_deliveryprice', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shop')),
                ('storage_product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Storage')),
            ],
        ),
    ]
