# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-26 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='storage_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Storage'),
        ),
    ]
