# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161226_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='storage_product',
        ),
        migrations.AddField(
            model_name='delivery',
            name='storage_product',
            field=models.ManyToManyField(to='main.Storage'),
        ),
    ]
