# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161227_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='storage_product',
            field=models.ManyToManyField(blank=True, null=True, to='main.Storage'),
        ),
    ]
