# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20161227_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
