# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_storage_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='custom_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_fromclient',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
