# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20161229_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='custom_price',
            field=models.IntegerField(blank=True),
        ),
    ]
