# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20161229_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='is_custom_price',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='is_custom_product',
            field=models.BooleanField(default=0),
        ),
    ]
