# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-07 21:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20170103_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 7, 21, 50, 55, 362613, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
