# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20170109_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystatus',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
