# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170109_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatusList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Delivery')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DeliveryStatus')),
            ],
        ),
        migrations.RemoveField(
            model_name='deliverylist',
            name='request',
        ),
        migrations.RemoveField(
            model_name='deliverylist',
            name='status',
        ),
        migrations.DeleteModel(
            name='DeliveryList',
        ),
    ]
