# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20170111_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='cash_transaction_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='storage_transaction_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
