# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20170111_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='cash_transaction_id',
            new_name='cash_id_transaction_id',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='storage_transaction_id',
            new_name='cash_out_transaction_id',
        ),
        migrations.AddField(
            model_name='delivery',
            name='storage_id_transaction_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='storage_out_transaction_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
