# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20170111_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelog',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
