# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-12 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_storagelog_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='creator_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
