# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-12 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_deliverylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylog',
            name='user',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
