# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-12 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_deliverylog_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylog',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Delivery'),
            preserve_default=False,
        ),
    ]
