# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_deliveryproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='storage_product',
        ),
    ]
